name: attack
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - matplotlib=3.10
  - numpy=1.26
  - pandas=2.2
  - joblib
  - pillow=11.1
  - python=3.10
  - pytorch=2.3
  - tensorboard=2.19
  - torchvision=0.18
  - tqdm=4.66
